Crear modelo de Book
wolox-training/gb-java pull request #3
Opened 2020-04-22 17:34 UTC by gbiriotti

## Summary
- Crear modelo de Book
## Trello Card
https://trello.com/c/6t4FUhH5

2020-04-22 19:13 UTC, leandrocostawolox requested changes
Buen trabajo, Gastón! Fuiste bastante más allá de lo que pedía la card, varios de estos puntos los vas a ir viendo en las próximas cards seguramente pero aproveché y lo corregí así ya queda. 
Te dejé algunos comentarios para que vayas leyendo y arreglando en este mismo branch.

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan("wolox.training.models")
En este caso con la annotation `@SpringBootApplication` alcanzaría, podemos eliminar `@EnableJpaRepositories` y `@EntityScan` porque Spring Boot automáticamente escanea por entidades y repositorios que se encuentren en el mismo package que se encuentra la aplicación que estamos ejecutando (Es decir, wolox.training). Y los packages de nuestros repositorios y entidades estarán ahí dentro.

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
>  @Controller
En realidad lo que vamos a usar es un RestController en lugar de un Controller, pero eso lo vamos a ver en otra card. Si querés lo corregimos luego :)

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
> +	@GetMapping("/api/books")
En este caso, podemos evitar darle una URI a GetMapping y directamente setearla sobre el nombre de la clase, es decir, quedaría:

```
@RestController
@RequestMapping("/api/books")
public class BookController {
```
Ya que todos los endpoints comenzarán con /api/books. Y luego, en este método directamente quedaría la annotation sin URI definida (Porque la define la clase):

```
@GetMapping
public Iterable<Book> findAll() {
```

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +	 */
Podemos eliminar estos comentarios si no vamos a usarlos

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +    }
No es necesario que creemos todos los constructores posibles, cuanto menos complejidad le demos a la construcción de nuestras abstracciones mejor :) Creo que en este caso podríamos ir por el constructor que pide el mensaje y el throwable, con eso estaríamos bien (Es decir, el segundo)

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +	 */
Podemos eliminar estos comentarios si no vamos a usarlos

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +    }
No es necesario que creemos todos los constructores posibles, cuanto menos complejidad le demos a la construcción de nuestras abstracciones mejor :) Creo que en este caso podríamos ir por el constructor que pide el mensaje y el throwable, con eso estaríamos bien (Es decir, el segundo)

2020-04-22 19:13 UTC, leandrocostawolox commented on src/test/java/wolox/training/TrainingApplicationTests.java
> +	 */
Lo ideal es nunca subir código comentado, ya que puede prestar a confusión a futuro (O si otro dev tiene que hacer modificaciones).
Esto incluso puede quedar descomentado, es un test por default que prueba que los contextos carguen correctamente y la aplicación corre sin ningún tipo de error

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +	@Column(nullable = true)
Esto está bien hecho! Pero dejo unos comentarios para mejorarlo :) 
Al haber anotado esta clase como `@Entity` ya no es necesario que anotemos al resto con `@Column`.
Para los `@Column(nullable = false)` existe la annotation `@NotNull` (de javax.validation.constraints.NotNull). La diferencia está en que con `@NotNull` JPA entra en acción atajando nulls antes de que lleguen a la base de datos (Con `@Column(nullable = false)` la validación directamente se haría en la base de datos. Si bien en el link de la card se utiliza `@Column`, vamos a preferir `@NotNull` para estos casos así evitamos el chequeo en la DB.

Este comentario aplica a todos los atributos de esta clase.

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +	}
Por lo pronto no necesitamos estos constructores, sí vamos a necesitar el constructor por defecto ya que JPA lo requiere para construir sus objetos:

```
    public Book() {

    }
```

Incluso el primero de los constructores nos construiría un objeto en un estado inválido para nuestro negocio, no querríamos tener un libro con datos en vacío y con cero páginas. Una buena práctica es sólo proveer constructores que generen objetos válidos para nuestro negocio (En el caso del constructor vacío nos contradecimos con esto jaja pero JPA lo requiere).
En cuanto a la annotation `@PersistenceConstructor`, JPA no la requiere, ya que suele utilizar el constructor vacío

2020-04-22 19:13 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +	}
El id de nuestros objetos lo va a manejar JPA, entonces queremos que sea lo más inmutable posible y que no pueda modificarse para evitar problemas. Por esto, lo mejor sería no tener un setter para el `id`

2020-04-23 12:03 UTC, gbiriotti commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan("wolox.training.models")
Entiendo lo que me comentas, según el tutorial que nos adjuntaba el card estaba explicito con esas anotaciones. Quizas se debea a que el tuto se realizo con una versión antigua de Spring que necesitaba estas anotaciones? Igualmente ya lo cambie.

2020-04-23 12:04 UTC, gbiriotti commented on src/main/java/wolox/training/controllers/BookController.java
>  @Controller
Ya lo cambie a @RestController.

2020-04-23 12:05 UTC, gbiriotti commented on src/main/java/wolox/training/controllers/BookController.java
> +	@GetMapping("/api/books")
Cambiado según lo comentado.

2020-04-23 12:05 UTC, gbiriotti commented on src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +	 */
Los elimine. Pensaba poner una descripción a la excepción y luego me olvide.

2020-04-23 12:05 UTC, gbiriotti commented on src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +    }
Modificado.

2020-04-23 12:05 UTC, gbiriotti commented on src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +    }
Modificado.

2020-04-23 12:06 UTC, gbiriotti commented on src/test/java/wolox/training/TrainingApplicationTests.java
> +	 */
Active el test y funciona correcto.

2020-04-23 12:08 UTC, gbiriotti commented on src/main/java/wolox/training/models/Book.java
> +	@Column(nullable = true)
Si, ya conocía las anotaciones pero al ver que el ejemplo del tutorial estaba realizado así pense que el objetivo era hacerlo de esa manera. Ya lo modifique.

2020-04-23 12:08 UTC, gbiriotti commented on src/main/java/wolox/training/models/Book.java
> +	}
Modificado.

2020-04-23 12:09 UTC, gbiriotti commented on src/main/java/wolox/training/models/Book.java
> +	}
Listo, elimine el set. Es lógico lo que me comentas, no me di cuenta de eso.

2020-04-23 14:46 UTC, gbiriotti commented
Modificaciones realizadas para: Crear modelo de Book (se adelanto generación Crear un Repositorio de Books.

2020-04-23 14:46 UTC, merged

2020-04-24 01:28 UTC, leandrocostawolox commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan("wolox.training.models")
En realidad esas annotations se siguen utilizando, pero como escribí en el comentario anterior, dependiendo de dónde tengamos nuestro código debemos o no agregarlas. Al estar todo dentro del mismo paquete no es necesario :) Pero si cualquiera de nosotros crea las clases en otro package, vamos a tener que usarlas

2020-04-24 01:29 UTC, leandrocostawolox commented on src/test/java/wolox/training/TrainingApplicationTests.java
> +	 */
Genial!!

2020-04-24 01:30 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +	@Column(nullable = true)
Perfecto! La idea es que pasen por `@Column` para después comentar el uso de `@NotNull` :)

2020-04-24 01:31 UTC, leandrocostawolox reviewed
Genial!